version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 frontend: #name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      #- "4200:4200" # specify port forewarding
      - "80:80"
      #- "443:443"
    container_name: front-container
    restart: always
 
 backend: #name of the second service
    build: server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    container_name: back-container
    restart: always
    links:
      - database # link this service to the database service
    depends_on:
       - database
 
 database: # name of the third service
  image: mongo # specify image to build container from
  ports:
  - "27017:27017" # specify port forwarding